# Generated by Django 5.1.7 on 2025-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrankaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_stranky', models.CharField(max_length=100)),
                ('pocet_nacteni', models.IntegerField(default=0)),
            ],
        ),
    ]
